### ISSUE TITLE
Unable to install, prompt error

### ISSUE THREAD

**Issue by hgq123** [CreativeDesigner3D/Library_Home_Builder#33]
▼0 Asset Library: Home Builder Library
描述:
Library designed to help with architectural and interior design
位置: 
Asset Library
文件: 
G:blender zxbiBlender283 3LTSwithPyClone\2 83'scriptsladdons)Home Builder Library_ init_ .Py
作者: 
Andrew Peel
版本:
0.1.0
报告:错误
A Traceback (most recent call last):
File "G:blender zxbiBlender283. 3LTSwithPyClone\2 83'scriptsrmodu lesladdon utils.py", line 351, in enable
mod =上import (module name)
File "G:blender zxb)Blender283_ 3LTSwithPyClonel2 .83\scriptsladdonsHome Builder Library init_ .py", line 7, in <module>
from. import home_ builder ops
File "G:lblender zxb)Blender283. 3LTSwithPyClone\2 .83)scripts\addonsHome Builder Libraryhome builder ops py", line 28, in <module>
from reportlab.pdfgen import canvas
ModuleNotFoundError: No module named 'reportlab'

**Comment by CreativeDesigner3D** [comment]
You need to run Home Builder with the new 2.90 install. Follow this article https://creativedesigner3d.com/2020/11/12/installing-blender-with-pyclone-2-90/
