### ISSUE TITLE
Cancelling placing Square Room asset, causes referencing error when trying to place after

### ISSUE THREAD

**Issue by onceadrog** [CreativeDesigner3D/Library_Home_Builder#73]
Cancelling placement of Square Room doesn't actually cancel it properly, elements are still placed, but badly referenced.

Steps to reproduce:
- Select Square Room asset
- In 3D view press P to place.
- Right click to cancel
- Press P to place, error occurs
- Leaves behind a bunch of elements including 32 vertices in the zero sized wall meshes
- Restart of Blender required to unbreak referencing
![image](https://user-images.githubusercontent.com/6299372/129636310-24150cf7-4f39-4873-8b53-88851ae8d573.png)

```
Error: Python: Traceback (most recent call last):
  File "C:\Users\Mike\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\PyClone-master\ops\pc_window_manager.py", line 32, in execute
    eval('bpy.ops.' + lib.drop_id + '("INVOKE_DEFAULT",filepath=path)')
  File "<string>", line 1, in <module>
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\bpy\ops.py", line 130, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Mike\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\Library_Home_Builder-master\home_builder_drop_ops.py", line 90, in execute
    bpy.ops.home_builder.place_room(filepath=self.filepath)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Mike\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\Library_Home_Builder-master\home_builder_drop_ops.py", line 169, in execute    self.get_object(context)
  File "C:\Users\Mike\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\Library_Home_Builder-master\home_builder_drop_ops.py", line 198, in get_object
    empty.hide_viewport = True
ReferenceError: StructRNA of type Object has been removed

location: C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\bpy\ops.py:132



location: C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\bpy\ops.py:130



location: <unknown location>:-1
```

**Comment by CreativeDesigner3D** [comment]
Thanks for the information. I will have this fixed in the next release.

**Comment by onceadrog** [comment]
Yeah, I see the wall drop ops isn't set up to handle the special case of the square room, like it does with simple wall.
And the cancelled placement doesn't seem visible to Blender for Undo, so restarting Blender is only fix.

Workaround: Do not right click to cancel, place and then delete instead.
