### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by iamminnian** [CreativeDesigner3D/Library_Home_Builder#75]
I'm getting the same error for all assets: (Products, Decorations, Materials and Build)

Python: Traceback (most recent call last):
  File "C:\Users\jon\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\home_builder\assets\products\sample_fixtures_bathroom\drop_ops_fixtures.py", line 34, in execute
    self.get_object(context)
  File "C:\Users\jon\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\home_builder\assets\products\sample_fixtures_bathroom\drop_ops_fixtures.py", line 51, in get_object
    path = os.path.join(sel_library.library_path,'assets',asset.file_data.name + ".blend")
AttributeError: 'NoneType' object has no attribute 'name'

**Comment by CreativeDesigner3D** [comment]
This has been fixed. Just click the check for updates button in the add-on. Also the new repository for Home Builder is here https://github.com/CreativeDesigner3D/home_builder. I'll be cleaning up my old repos soon.
